### ISSUE TITLE
RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by boral** [questdb/py-questdb-query#2]
I got runtimeerror. Trying to fetch from localhost.

```
from questdb_query import pandas_query
tt = pandas_query('select * from sensors limit 1000')
```

![image](https://github.com/questdb/py-questdb-query/assets/12884971/b0cbcfeb-e11a-4cee-9fad-bfa09127987b)

**Comment by amunra** [comment]
Sorry. I missed this.
See: https://github.com/questdb/py-questdb-query?tab=readme-ov-file#async-operation

If you already have an event loop running you should use the async variants.
